audit_header: false
title: San Diego Real Estate Video Blog with Sparky and Katie Pond
description: Our mission at Pond Team is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Pond Team, your professional San Diego Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Sparky and Katie Pond
  title:
  license_number: 'DRE #01372991'
  about_markdown: |
    Two standouts in their field, Sparky and Katie Pond have earned a reputation for leading with honesty, integrity, and transparency. Armed with a combined 28 years of real estate experience, the dynamic husband and wife duo have no lack of success stories. "5 stars is not enough to express how impressed I am with their service," raves one former client, while another shares, "nothing less than absolutely amazing." Two top performers in the industry, both Realtors have garnered extremely high levels of client satisfaction.
  brand: Pond Team
  brokerage: Compass
  market: San Diego
  address: 617 Saxony Pl ST 101, Encinitas, CA 92024
  phone: 760-402-2865
  phone_type:
  phone2:
  phone2_type:
  email: pondteam@compass.com
  url: http://www.pondteamrealestate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.compass.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.compass.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pondteamrealestate/
  linkedin_url: https://www.linkedin.com/in/pondteamrealestate/
  youtube_url: https://www.youtube.com/channel/UCExg7x7_MxF0eULTH6nShZA
  twitter_url: https://twitter.com/PondTeamRE
  instagram_url: https://www.instagram.com/katiensparky/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Diego Real Estate Podcast with Sparky and Katie Pond'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Pond Team - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Sparky and Katie Pond'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#999'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#f5e4c6'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
